
# SEO settings
title: "Chris"
title2: "Evett" # default: ""
description: "Chris Evett's devops blog"
keywords: "DevOps, blog, troubleshooting, continuous delivery"
url: http://www.chrisevett.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

repo: http://github.com/chrisevett/chrisevett.github.io
twitter_username: "chris_evett"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Chris Evett"
  job      : "Infrastructure engineer and Devops enthusiast"
  bio      : "Software is garbage and I'm the garbage man."
  email    : chris.evett@gmail.com
  url      : http://www.chrisevett.com
  github   : http://github.com/chrisevett
  twitter  : http://twitter.com/chris_evett
  linkedin : https://www.linkedin.com/in/chris-evett-22954138

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@chris_evett"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
